# version: "3"

networks:
  viziquer-network:
    name: "viziquer-tools"

services:
  viziquer:
    image: ghcr.io/lumii-syslab/viziquer:development
    depends_on:
      - mongodb
      - dss
    ports:
      - "${VIZIQUER_PORT}:3000"
    container_name: viziquer
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongodb:27017/${MONGODB_DATABASE}
      - ROOT_URL=http://127.0.0.1
      - PORT=3000
      - STARTUP_DELAY=10
      - SCHEMA_SERVER_URL=http://localhost:${DSS_PORT}/api
      - REAL_SCHEMA_SERVER_URL=http://dss:${DSS_PORT}/api
    networks:
      - viziquer-network

  mongodb:
    image: mongo:6
    restart: unless-stopped
    container_name: mongodb
    volumes:
      - ./db/mongo:/data/db
      - ./db/init/mongo:/docker-entrypoint-initdb.d
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      # MONGO_INITDB_ROOT_DATABASE: ${MONGODB_DATABASE}
      # MONGODB_PORT: 27017
    networks:
      - viziquer-network

  dss:
    image: ghcr.io/lumii-syslab/data-shape-server:main
    container_name: dss
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - ${DSS_PORT}:3030
    environment:
      - NODE_ENV=production
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/rdfmeta
      - PORT=3030
    networks:
      - viziquer-network

  postgres:
    image: postgres:17
    restart: unless-stopped
    container_name: postgres
    shm_size: 128mb
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./db/pg:/var/lib/postgresql/data
      - ./data/pg-dumps:/dumps
      - ./db/init/pg:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
    networks:
      - viziquer-network

  pgadmin:
    image: dpage/pgadmin4:8.12.0
    restart: unless-stopped
    ports:
      - ${PGADMIN_PORT}:80
      # - 9003:443
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_DISABLE_POSTFIX=true
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    volumes:
      - ./config/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - viziquer-network
